# Generated by Django 2.1.7 on 2019-04-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0002_auto_20190407_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='predmet',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='predmet',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lessons',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Predmet',
        ),
    ]
