# Generated by Django 2.1.7 on 2019-04-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0005_auto_20190425_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ManyToManyField(to='journalapp.Subject'),
        ),
    ]
