# Generated by Django 2.1.7 on 2019-04-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0006_auto_20190425_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='subject',
            new_name='subjects',
        ),
    ]
