# Generated by Django 2.1.7 on 2019-04-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0007_auto_20190425_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subjects',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subjects',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='journalapp.Subject'),
        ),
    ]
