# Generated by Django 2.1.7 on 2019-04-27 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0012_auto_20190427_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='journals',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='students',
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journalapp.Student'),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journalapp.Subject'),
        ),
    ]
