# Generated by Django 2.1.7 on 2019-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0013_auto_20190427_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
