# Generated by Django 2.1.7 on 2019-04-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0014_auto_20190427_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='id',
            field=models.IntegerField(null=True),
        ),
    ]
