# Generated by Django 2.1.7 on 2019-04-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0015_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
    ]
