# Generated by Django 2.1.7 on 2019-04-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0017_auto_20190427_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='id',
            field=models.IntegerField(serialize=False,auto_created=True,primary_key=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
