# Generated by Django 2.1.7 on 2019-04-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0018_auto_20190427_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
