# Generated by Django 2.1.7 on 2019-04-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0020_auto_20190427_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.CharField(max_length=2),
        ),
    ]
