# Generated by Django 2.1.7 on 2019-08-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journalapp', '0021_auto_20190429_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('can_edit_marks', 'edit marks'),)},
        ),
    ]
